---
# Source: signalfx-agent/templates/configmap-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: signalfx-agent
  namespace: default
  labels:
    app: signalfx-agent
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
  - create
